### ISSUE TITLE
icr.io/cpopen/datapower-operator-conversion-webhook Image

### ISSUE THREAD

**Issue by hadarnir33** [IBM/datapower-operator-chart#13]
Hey, the operator is deploying icr.io/cpopen/datapower-operator-conversion-webhook pod but this image name is not configurable (at least I didn't find a place to config it), so I can't point to my own private docker registry to pull the image from.
Thanks

**Comment by aharbis** [comment]
Hi @hadarnir33, there is a mechanism to override the webhook image using an environment variable on the main operator pod:

https://ibm.github.io/datapower-operator-doc/features/webhooks/#image-override
